#define STL_NOT_BINARY -1
#define NO_FILE -2
#define FILE_NOT_OPEN -3
#define NO_DR -4
#define READ_ERROR -5
#define FLUID_NDEF -6
#define WRITE_FAIL -7
#define SORT_NOT_CLOSED -8
#define NO_PER_VERT -9
#define NO_UNLINK -10
